<?php

/**
 * @file
 * Contains opera_brevis_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opera_brevis_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opera_brevis_module module.
    case 'help.page.opera_brevis_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module for Opera Brevis') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opera_brevis_module_theme() {
  return [
    'opera_brevis_module' => [
      'render element' => 'children',
    ],
    'footer_logo' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
    'footer_login' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],

    'footer_unterstuetzen' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],

  ];
}
