<?php

/**
 * @file
 * Contains opera_brevis_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function opera_brevis_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opera_brevis_module module.
    case 'help.page.opera_brevis_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module for Opera Brevis') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opera_brevis_module_theme() {
  return [
    'opera_brevis_module' => [
      'render element' => 'children',
    ],
    'footer_logo' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'footer_login' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],

    'footer_unterstuetzen' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],

  ];
}

/**
 * Implements hook_page_attachments().
 */
function opera_brevis_module_page_attachments(array &$attachments) {
  $roles = \Drupal::currentUser()->getRoles();

  if (in_array('mollo_editor', $roles, TRUE)) {
    $attachments['#attached']['library'][] = 'opera_brevis_module/opera_brevis_module.main';
  }
}


/**
 * Implements hook_toolbar().
 *
 * Hack: link to dashboard via opera-brevis-module.js in opera brevis theme
 *
 */
function opera_brevis_module_toolbar() {
  $items['mollo_dashboard'] = [
    '#cache' => [
      'contexts' => ['user.roles'],
    ],
  ];

  $roles = \Drupal::currentUser()->getRoles();

  if (in_array('mollo_editor', $roles, TRUE)) {
    $items['mollo_dashboard'] += [
      '#weight' => 888,
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('Dashboard'),
        '#url' => Url::fromUri('internal:/admin/dashboard'),
        '#attributes' => [
          'title' => t('Eine übersicht der Einträge'),
          'class' => [
            'toolbar-icon',
            'toolbar-icon-dashboard',
          ],

        ],
      ],
      'tray' => [
        '#heading' => t('User messages'),
        'messages' => [],
      ],
      // Custom CSS, JS or a library can be associated with the toolbar item.
      '#attached' => [
        'library' => [
          'opera_brevis_module/opera_brevis_module.admin',
        ],
      ],
    ];

  }

  return $items;
}
